//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games_Project_Noughts_And_Crosses
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainLeaderboard2
    {
        public int Id { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
    }
}
